dataloader:
  evaluator: {_target_: detectron2.evaluation.COCOEvaluator, dataset_name: '${..test.dataset.names}'}
  test:
    _target_: detectron2.data.build_detection_test_loader
    dataset: {_target_: detectron2.data.get_detection_dataset_dicts, filter_empty: false, names: fashionpedia_val}
    mapper:
      _target_: detectron2.data.DatasetMapper
      augmentations:
      - {_target_: detectron2.data.transforms.ResizeShortestEdge, max_size: 1333, short_edge_length: 800}
      image_format: ${...train.mapper.image_format}
      is_train: false
    num_workers: 0
  train:
    _target_: detectron2.data.build_detection_train_loader
    dataset: {_target_: detectron2.data.get_detection_dataset_dicts, names: fashionpedia_train}
    mapper:
      _target_: detectron2.data.DatasetMapper
      augmentations:
      - {_target_: detectron2.data.transforms.ResizeScale, max_scale: 2.0, min_scale: 0.5, target_height: 1024, target_width: 1024}
      - _target_: detectron2.data.transforms.FixedSizeCrop
        crop_size: [1024, 1024]
      - {_target_: detectron2.data.transforms.RandomFlip, horizontal: true}
      image_format: BGR
      is_train: true
      recompute_boxes: true
      use_instance_mask: true
    num_workers: 0
    total_batch_size: 8
model:
  _target_: detectron2.modeling.GeneralizedRCNN
  backbone:
    _target_: detectron2.modeling.FPN
    bottom_up:
      _target_: detectron2.modeling.backbone.RegNet
      block_class: !!python/name:detectron2.modeling.backbone.regnet.ResBottleneckBlock ''
      depth: 22
      group_width: 64
      norm: BN
      out_features: [s1, s2, s3, s4]
      se_ratio: 0.25
      stem_class: !!python/name:detectron2.modeling.backbone.regnet.SimpleStem ''
      stem_width: 32
      w_0: 96
      w_a: 31.41
      w_m: 2.24
    in_features: ${.bottom_up.out_features}
    norm: BN
    out_channels: 256
    top_block: {_target_: detectron2.modeling.backbone.fpn.LastLevelMaxPool}
  input_format: BGR
  pixel_mean: [103.53, 116.28, 123.675]
  pixel_std: [57.375, 57.12, 58.395]
  proposal_generator:
    _target_: detectron2.modeling.proposal_generator.RPN
    anchor_generator:
      _target_: detectron2.modeling.anchor_generator.DefaultAnchorGenerator
      aspect_ratios: [0.5, 1.0, 2.0]
      offset: 0.0
      sizes:
      - [32]
      - [64]
      - [128]
      - [256]
      - [512]
      strides: [4, 8, 16, 32, 64]
    anchor_matcher:
      _target_: detectron2.modeling.matcher.Matcher
      allow_low_quality_matches: true
      labels: [0, -1, 1]
      thresholds: [0.3, 0.7]
    batch_size_per_image: 256
    box2box_transform:
      _target_: detectron2.modeling.box_regression.Box2BoxTransform
      weights: [1.0, 1.0, 1.0, 1.0]
    head:
      _target_: detectron2.modeling.proposal_generator.StandardRPNHead
      conv_dims: [-1, -1]
      in_channels: 256
      num_anchors: 3
    in_features: [p2, p3, p4, p5, p6]
    nms_thresh: 0.7
    positive_fraction: 0.5
    post_nms_topk: [1000, 1000]
    pre_nms_topk: [2000, 1000]
  roi_heads:
    _target_: detectron2.modeling.StandardROIHeads
    batch_size_per_image: 256
    box_head:
      _target_: detectron2.modeling.roi_heads.FastRCNNConvFCHead
      conv_dims: [256, 256, 256, 256]
      conv_norm: BN
      fc_dims: [1024]
      input_shape: !!python/object/new:detectron2.layers.shape_spec.ShapeSpec [256, 7, 7, null]
    box_in_features: [p2, p3, p4, p5]
    box_pooler:
      _target_: detectron2.modeling.poolers.ROIPooler
      output_size: 7
      pooler_type: ROIAlignV2
      sampling_ratio: 0
      scales: [0.25, 0.125, 0.0625, 0.03125]
    box_predictor:
      _target_: detectron2.modeling.FastRCNNOutputLayers
      box2box_transform:
        _target_: detectron2.modeling.box_regression.Box2BoxTransform
        weights: [10, 10, 5, 5]
      input_shape: !!python/object/new:detectron2.layers.shape_spec.ShapeSpec [1024, null, null, null]
      num_classes: ${..num_classes}
      test_score_thresh: 0.05
    mask_head:
      _target_: detectron2.modeling.roi_heads.MaskRCNNConvUpsampleHead
      conv_dims: [256, 256, 256, 256, 256]
      conv_norm: BN
      input_shape: !!python/object/new:detectron2.layers.shape_spec.ShapeSpec [256, 14, 14, null]
      num_classes: ${..num_classes}
    mask_in_features: [p2, p3, p4, p5]
    mask_pooler:
      _target_: detectron2.modeling.poolers.ROIPooler
      output_size: 14
      pooler_type: ROIAlignV2
      sampling_ratio: 0
      scales: [0.25, 0.125, 0.0625, 0.03125]
    num_classes: 46
    positive_fraction: 0.25
    proposal_matcher:
      _target_: detectron2.modeling.matcher.Matcher
      allow_low_quality_matches: false
      labels: [0, 1]
      thresholds: [0.5]
optimizer:
  _target_: torch.optim.SGD
  lr: 0.001
  momentum: 0.9
  params: {_target_: detectron2.solver.get_default_optimizer_params, weight_decay_norm: 0.0}
  weight_decay: 4.0e-05
lr_multiplier:
  _target_: detectron2.solver.WarmupParamScheduler
  scheduler:
    _target_: fvcore.common.param_scheduler.MultiStepParamScheduler
    milestones: [7000, 9000]
    num_updates: 10000
    values: [1.0, 0.1, 0.01]
  warmup_factor: 0.1
  warmup_length: 0.002
train:
  amp: {enabled: true}
  checkpointer: {max_to_keep: 100, period: 2000}
  cudnn_benchmark: true
  device: cuda
  eval_period: 57
  init_checkpoint: https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_regnety_4gf_dds_FPN_100ep_LSJ/42047784/model_final_6ba57e.pkl
  log_period: 50
  max_iter: 10000
  output_dir: ./output
